name: iOS Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode_16.2.app
        
      - name: Reset & Boot Simulator
        run: |
          xcrun simctl shutdown all
          xcrun simctl erase all
          xcrun simctl boot "iPhone 16 Pro"
          sleep 120

      - name: Build and Test
        run: |
          xcodebuild test \
            -scheme ExpenseTracker \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=18.2' \
            ONLY_ACTIVE_ARCH=YES
            -only-testing:ExpenseTrackerTests

